// Seed Data for Patel Sahab Spices Marketing Management System

export const INITIAL_PRODUCTS = [
  { id: 'p-1', name: 'Mirchi Powder', packSizes: ['50g', '100g', '200g', '500g', '1kg'], ratePerKg: 240, category: 'Pure Spices' },
  { id: 'p-2', name: 'Haldi Powder', packSizes: ['50g', '100g', '200g', '500g', '1kg'], ratePerKg: 180, category: 'Pure Spices' },
  { id: 'p-3', name: 'Dhaniya Powder', packSizes: ['50g', '100g', '200g', '500g', '1kg'], ratePerKg: 160, category: 'Pure Spices' },
  { id: 'p-4', name: 'Garam Masala', packSizes: ['50g', '100g', '200g', '500g'], ratePerKg: 450, category: 'Blended Spices' },
  { id: 'p-5', name: 'Sabji Masala', packSizes: ['50g', '100g', '200g', '500g'], ratePerKg: 280, category: 'Blended Spices' },
  { id: 'p-6', name: 'Chicken Masala', packSizes: ['50g', '100g', '200g'], ratePerKg: 320, category: 'Blended Spices' },
  { id: 'p-7', name: 'Kasturi Methi', packSizes: ['25g', '50g', '100g'], ratePerKg: 380, category: 'Herbs' },
];

// Master list of all ~100 Market Groups, Townships, Routes & Mandis
export const MASTER_MARKET_GROUPS = [
  'Kalapipal',
  'Arniya Kalan',
  'Kolwa',
  'Chakrod',
  'Behrawal',
  'Nandani',
  'Kurawar',
  'Khokra Kalan',
  'Khardon',
  'Farad',
  'Khamlay',
  'Nipaniya',
  'Pochaner',
  'Ghatti',
  'Shujalpur',
  'Bhesaya Gada',
  'Aanliya Jod',
  'Talen',
  'Agkhedi',
  'Guna',
  'Badodiya',
  'Jamner',
  'Akodia',
  'Kamalpur',
  'Iklera',
  'Polay Kalan',
  'Pagarawad',
  'Kalapipal Gav',
  'Gulana',
  'Mohmmad Kheda',
  'Salsalai',
  'Arandiya Jod',
  'Lalakhedi',
  'Lasuldiya Malak',
  'Stikar',
  'Jhadla',
  'Sarangpur',
  'Dhabla Dheer',
  'Parwati Nagar',
  'Ashta',
  'Kadwala',
  'Khedawad',
  'Pachore',
  'Boda',
  'Kotari',
  'Berchha Dattar',
  'Shujalpur City',
  'Shujalpur Freegang',
  'Indore',
  'Hadlay Jod',
  'Semliya',
  'Ugli',
  'Rosla',
  'Shyampur',
  'Chandbad',
  'Amlaha',
  'Sehore',
  'Lasudiya Bijasi',
  'Nanakpur',
  'Bolai',
  'Khujner',
  'Kotari Astha',
  'Mohan Badodiya',
  'Khandwa',
  'Doraha',
  'Choki',
  'Ichhawar',
  'Ahmadpur',
  'Haldi Vendor',
  'Pouch',
  'Mirch',
  'Dhaniya',
  'Dhamna',
  'Raipur',
  'Lasuldiya Gori',
  'Dewas Bus Stand',
  'Binaya',
  'Tilawat',
  'Nipaniya Jod',
  'Dewas Vikash Nagar',
  'Dewas Itawa',
  'Dewas Balgrah',
  'Dewas Aawas Colony',
  'Bhilkheda',
  'Bhilkhedi',
  'Sandawata',
  'Nahali',
  'Panvadi',
  'Bakkhedi',
  'Datotar',
  'Bhav Khedi',
  'Khatsur',
  'Hakimabad',
  'Merkhedi',
  'Bhakkhedi',
  'Roshi',
  'Hatpipliya',
  'Bakaniya',
  'Sajankhedi',
  'Ujjain',
  'Dendi Jod',
];

// --- MASTER MARKET LIST ---
export const INITIAL_MARKETS = [
  { id: 'mkt-pachore', name: 'Pachore', district: 'Rajgarh', distanceKm: 80, fuelRateKm: 2, maxFuelAllowed: 160, totalShops: 30, assignedMarketerId: 'marketer-1', assignedMarketerName: 'Deepak Prajapati' },
  { id: 'mkt-ashta', name: 'Ashta', district: 'Sehore', distanceKm: 65, fuelRateKm: 2, maxFuelAllowed: 130, totalShops: 25, assignedMarketerId: 'marketer-2', assignedMarketerName: 'Vijay Verma' },
  { id: 'mkt-kalapipal', name: 'Kalapipal', district: 'Shajapur', distanceKm: 45, fuelRateKm: 2, maxFuelAllowed: 90, totalShops: 20, assignedMarketerId: 'marketer-3', assignedMarketerName: 'Atul Meena' },
  { id: 'mkt-shujalpur', name: 'Shujalpur', district: 'Shajapur', distanceKm: 55, fuelRateKm: 2, maxFuelAllowed: 110, totalShops: 22, assignedMarketerId: 'marketer-4', assignedMarketerName: 'Pankaj Malviya' },
  { id: 'mkt-sarangpur', name: 'Sarangpur', district: 'Rajgarh', distanceKm: 70, fuelRateKm: 2, maxFuelAllowed: 140, totalShops: 24, assignedMarketerId: 'marketer-5', assignedMarketerName: 'Vikash Meena' },
  { id: 'mkt-biaora', name: 'Biaora', district: 'Rajgarh', distanceKm: 85, fuelRateKm: 2, maxFuelAllowed: 170, totalShops: 28, assignedMarketerId: 'marketer-1', assignedMarketerName: 'Deepak Prajapati' },
  { id: 'mkt-akodia', name: 'Akodia', district: 'Shajapur', distanceKm: 50, fuelRateKm: 2, maxFuelAllowed: 100, totalShops: 23, assignedMarketerId: 'marketer-1', assignedMarketerName: 'Deepak Prajapati' },
  { id: 'mkt-chakrod', name: 'Chakrod', district: 'Shajapur', distanceKm: 40, fuelRateKm: 2, maxFuelAllowed: 80, totalShops: 18, assignedMarketerId: 'marketer-4', assignedMarketerName: 'Pankaj Malviya' },
  { id: 'mkt-jamner', name: 'Jamner', district: 'Shajapur', distanceKm: 60, fuelRateKm: 2, maxFuelAllowed: 120, totalShops: 15, assignedMarketerId: 'marketer-3', assignedMarketerName: 'Atul Meena' },
  { id: 'mkt-gulana', name: 'Gulana', district: 'Shajapur', distanceKm: 35, fuelRateKm: 2, maxFuelAllowed: 70, totalShops: 16, assignedMarketerId: 'marketer-2', assignedMarketerName: 'Vijay Verma' },
  { id: 'mkt-mohammad-kheda', name: 'Mohammad Kheda', district: 'Shajapur', distanceKm: 48, fuelRateKm: 2, maxFuelAllowed: 96, totalShops: 12, assignedMarketerId: 'marketer-5', assignedMarketerName: 'Vikash Meena' },
  { id: 'mkt-bolai', name: 'Bolai', district: 'Shajapur', distanceKm: 52, fuelRateKm: 2, maxFuelAllowed: 104, totalShops: 14, assignedMarketerId: 'marketer-1', assignedMarketerName: 'Deepak Prajapati' },
  { id: 'mkt-tarana', name: 'Tarana', district: 'Ujjain', distanceKm: 75, fuelRateKm: 2, maxFuelAllowed: 150, totalShops: 20, assignedMarketerId: 'marketer-2', assignedMarketerName: 'Vijay Verma' },
  { id: 'mkt-shajapur', name: 'Shajapur', district: 'Shajapur', distanceKm: 30, fuelRateKm: 2, maxFuelAllowed: 60, totalShops: 35, assignedMarketerId: 'marketer-4', assignedMarketerName: 'Pankaj Malviya' },
];

// --- NEW: LEVEL 1 – MARKET ROUTES ---
// Each route is a named territory that a marketer is assigned to.
export const INITIAL_MARKET_ROUTES = [
  { id: 'route-pachore', name: 'Pachore', active: true, notes: 'Rajgarh District – main Pachore territory' },
  { id: 'route-ashta', name: 'Ashta', active: true, notes: 'Sehore District – Ashta territory' },
  { id: 'route-kalapipal', name: 'Kalapipal', active: true, notes: 'Shajapur District – Kalapipal area' },
  { id: 'route-shujalpur', name: 'Shujalpur', active: true, notes: 'Shajapur District – Shujalpur area' },
  { id: 'route-sarangpur', name: 'Sarangpur', active: true, notes: 'Rajgarh District – Sarangpur area' },
  { id: 'route-biaora', name: 'Biaora', active: true, notes: 'Rajgarh District – Biaora area' },
];

// --- NEW: LEVEL 2 – CONNECTED MARKETS (sub-markets within each route) ---
// Each connected market is an individual town/village/mandi visited within a route.
export const INITIAL_CONNECTED_MARKETS = [
  // Pachore Route connected markets
  { id: 'cm-pachore-01', routeId: 'route-pachore', routeName: 'Pachore', name: 'Pachore', active: true, distanceKm: 80, priority: 1 },
  { id: 'cm-pachore-02', routeId: 'route-pachore', routeName: 'Pachore', name: 'Berchha', active: true, distanceKm: 75, priority: 2 },
  { id: 'cm-pachore-03', routeId: 'route-pachore', routeName: 'Pachore', name: 'Narsinghgarh', active: true, distanceKm: 90, priority: 3 },

  // Ashta Route connected markets
  { id: 'cm-ashta-01', routeId: 'route-ashta', routeName: 'Ashta', name: 'Ashta', active: true, distanceKm: 65, priority: 1 },
  { id: 'cm-ashta-02', routeId: 'route-ashta', routeName: 'Ashta', name: 'Kannod', active: true, distanceKm: 70, priority: 2 },
  { id: 'cm-ashta-03', routeId: 'route-ashta', routeName: 'Ashta', name: 'Sehore', active: true, distanceKm: 60, priority: 3 },

  // Kalapipal Route connected markets
  { id: 'cm-kalapipal-01', routeId: 'route-kalapipal', routeName: 'Kalapipal', name: 'Kalapipal', active: true, distanceKm: 45, priority: 1 },
  { id: 'cm-kalapipal-02', routeId: 'route-kalapipal', routeName: 'Kalapipal', name: 'Susner', active: true, distanceKm: 50, priority: 2 },

  // Shujalpur Route connected markets
  { id: 'cm-shujalpur-01', routeId: 'route-shujalpur', routeName: 'Shujalpur', name: 'Shujalpur', active: true, distanceKm: 55, priority: 1 },
  { id: 'cm-shujalpur-02', routeId: 'route-shujalpur', routeName: 'Shujalpur', name: 'Agar', active: true, distanceKm: 60, priority: 2 },

  // Sarangpur Route connected markets
  { id: 'cm-sarangpur-01', routeId: 'route-sarangpur', routeName: 'Sarangpur', name: 'Sarangpur', active: true, distanceKm: 70, priority: 1 },
  { id: 'cm-sarangpur-02', routeId: 'route-sarangpur', routeName: 'Sarangpur', name: 'Rajgarh', active: true, distanceKm: 65, priority: 2 },

  // Biaora Route connected markets
  { id: 'cm-biaora-01', routeId: 'route-biaora', routeName: 'Biaora', name: 'Biaora', active: true, distanceKm: 85, priority: 1 },
  { id: 'cm-biaora-02', routeId: 'route-biaora', routeName: 'Biaora', name: 'Khilchipur', active: true, distanceKm: 90, priority: 2 },
];

export const INITIAL_MARKETERS = [
  { id: 'marketer-1', name: 'Deepak Prajapati', mobile: '9826012345', email: 'deepak@patelsahab.com',  active: true, joinedDate: '01-01-2025' },
  { id: 'marketer-2', name: 'Vijay Verma',       mobile: '9826023456', email: 'vijay@patelsahab.com',   active: true, joinedDate: '15-02-2025' },
  { id: 'marketer-3', name: 'Atul Meena',         mobile: '9826034567', email: 'atul@patelsahab.com',    active: true, joinedDate: '10-03-2025' },
  { id: 'marketer-4', name: 'Pankaj Malviya',     mobile: '9826045678', email: 'pankaj@patelsahab.com', active: true, joinedDate: '01-04-2025' },
  { id: 'marketer-5', name: 'Vikash Meena',       mobile: '9826056789', email: 'vikash@patelsahab.com', active: true, joinedDate: '15-04-2025' },
];


export const INITIAL_WEEKLY_ROUTES = [
  // Deepak Prajapati
  { marketerId: 'marketer-1', day: 'Monday', marketId: 'mkt-pachore', marketName: 'Pachore', routeId: 'route-pachore', connectedMarketId: 'cm-pachore-01' },
  { marketerId: 'marketer-1', day: 'Tuesday', marketId: 'mkt-ashta', marketName: 'Ashta', routeId: 'route-ashta', connectedMarketId: 'cm-ashta-01' },
  { marketerId: 'marketer-1', day: 'Wednesday', marketId: 'mkt-kalapipal', marketName: 'Kalapipal', routeId: 'route-kalapipal', connectedMarketId: 'cm-kalapipal-01' },
  { marketerId: 'marketer-1', day: 'Thursday', marketId: 'mkt-shujalpur', marketName: 'Shujalpur', routeId: 'route-shujalpur', connectedMarketId: 'cm-shujalpur-01' },
  { marketerId: 'marketer-1', day: 'Friday', marketId: 'mkt-sarangpur', marketName: 'Sarangpur', routeId: 'route-sarangpur', connectedMarketId: 'cm-sarangpur-01' },
  { marketerId: 'marketer-1', day: 'Saturday', marketId: 'mkt-biaora', marketName: 'Biaora', routeId: 'route-biaora', connectedMarketId: 'cm-biaora-01' },

  // Vijay Verma
  { marketerId: 'marketer-2', day: 'Monday', marketId: 'mkt-ashta', marketName: 'Ashta', routeId: 'route-ashta', connectedMarketId: 'cm-ashta-01' },
  { marketerId: 'marketer-2', day: 'Tuesday', marketId: 'mkt-pachore', marketName: 'Pachore', routeId: 'route-pachore', connectedMarketId: 'cm-pachore-01' },
  { marketerId: 'marketer-2', day: 'Wednesday', marketId: 'mkt-shujalpur', marketName: 'Shujalpur', routeId: 'route-shujalpur', connectedMarketId: 'cm-shujalpur-01' },
  { marketerId: 'marketer-2', day: 'Thursday', marketId: 'mkt-kalapipal', marketName: 'Kalapipal', routeId: 'route-kalapipal', connectedMarketId: 'cm-kalapipal-01' },
  { marketerId: 'marketer-2', day: 'Friday', marketId: 'mkt-biaora', marketName: 'Biaora', routeId: 'route-biaora', connectedMarketId: 'cm-biaora-01' },
  { marketerId: 'marketer-2', day: 'Saturday', marketId: 'mkt-sarangpur', marketName: 'Sarangpur', routeId: 'route-sarangpur', connectedMarketId: 'cm-sarangpur-01' },

  // Atul Meena
  { marketerId: 'marketer-3', day: 'Monday', marketId: 'mkt-kalapipal', marketName: 'Kalapipal', routeId: 'route-kalapipal', connectedMarketId: 'cm-kalapipal-01' },
  { marketerId: 'marketer-3', day: 'Tuesday', marketId: 'mkt-shujalpur', marketName: 'Shujalpur', routeId: 'route-shujalpur', connectedMarketId: 'cm-shujalpur-01' },
  { marketerId: 'marketer-3', day: 'Wednesday', marketId: 'mkt-pachore', marketName: 'Pachore', routeId: 'route-pachore', connectedMarketId: 'cm-pachore-01' },
  { marketerId: 'marketer-3', day: 'Thursday', marketId: 'mkt-ashta', marketName: 'Ashta', routeId: 'route-ashta', connectedMarketId: 'cm-ashta-01' },
  { marketerId: 'marketer-3', day: 'Friday', marketId: 'mkt-sarangpur', marketName: 'Sarangpur', routeId: 'route-sarangpur', connectedMarketId: 'cm-sarangpur-01' },
  { marketerId: 'marketer-3', day: 'Saturday', marketId: 'mkt-biaora', marketName: 'Biaora', routeId: 'route-biaora', connectedMarketId: 'cm-biaora-01' },

  // Pankaj Malviya
  { marketerId: 'marketer-4', day: 'Monday', marketId: 'mkt-shujalpur', marketName: 'Shujalpur', routeId: 'route-shujalpur', connectedMarketId: 'cm-shujalpur-01' },
  { marketerId: 'marketer-4', day: 'Tuesday', marketId: 'mkt-kalapipal', marketName: 'Kalapipal', routeId: 'route-kalapipal', connectedMarketId: 'cm-kalapipal-01' },
  { marketerId: 'marketer-4', day: 'Wednesday', marketId: 'mkt-ashta', marketName: 'Ashta', routeId: 'route-ashta', connectedMarketId: 'cm-ashta-01' },
  { marketerId: 'marketer-4', day: 'Thursday', marketId: 'mkt-pachore', marketName: 'Pachore', routeId: 'route-pachore', connectedMarketId: 'cm-pachore-01' },
  { marketerId: 'marketer-4', day: 'Friday', marketId: 'mkt-biaora', marketName: 'Biaora', routeId: 'route-biaora', connectedMarketId: 'cm-biaora-01' },
  { marketerId: 'marketer-4', day: 'Saturday', marketId: 'mkt-sarangpur', marketName: 'Sarangpur', routeId: 'route-sarangpur', connectedMarketId: 'cm-sarangpur-01' },

  // Vikash Meena
  { marketerId: 'marketer-5', day: 'Monday', marketId: 'mkt-sarangpur', marketName: 'Sarangpur', routeId: 'route-sarangpur', connectedMarketId: 'cm-sarangpur-01' },
  { marketerId: 'marketer-5', day: 'Tuesday', marketId: 'mkt-biaora', marketName: 'Biaora', routeId: 'route-biaora', connectedMarketId: 'cm-biaora-01' },
  { marketerId: 'marketer-5', day: 'Wednesday', marketId: 'mkt-pachore', marketName: 'Pachore', routeId: 'route-pachore', connectedMarketId: 'cm-pachore-01' },
  { marketerId: 'marketer-5', day: 'Thursday', marketId: 'mkt-ashta', marketName: 'Ashta', routeId: 'route-ashta', connectedMarketId: 'cm-ashta-01' },
  { marketerId: 'marketer-5', day: 'Friday', marketId: 'mkt-kalapipal', marketName: 'Kalapipal', routeId: 'route-kalapipal', connectedMarketId: 'cm-kalapipal-01' },
  { marketerId: 'marketer-5', day: 'Saturday', marketId: 'mkt-shujalpur', marketName: 'Shujalpur', routeId: 'route-shujalpur', connectedMarketId: 'cm-shujalpur-01' },
];

export const INITIAL_SHOPS = [
  // Pachore Shops
  { id: 'shop-p1', name: 'Sawariya Kirana Store', owner: 'Ramesh Gupta', mobile: '9425011111', address: 'Main Market Road, Pachore', marketId: 'mkt-pachore', routeId: 'route-pachore', connectedMarketId: 'cm-pachore-01', status: 'Customer', outstanding: 5200, lastOrderKg: 18, lastOrderDate: '11-08-2026', highReturnWarning: false, lat: 23.7021, lng: 76.7112 },
  { id: 'shop-p2', name: 'Patidar Kirana Store', owner: 'Suresh Patidar', mobile: '9425022222', address: 'Bus Stand Square, Pachore', marketId: 'mkt-pachore', routeId: 'route-pachore', connectedMarketId: 'cm-pachore-01', status: 'Customer', outstanding: 12500, lastOrderKg: 38, lastOrderDate: '11-08-2026', highReturnWarning: true, lat: 23.7035, lng: 76.7125 },
  { id: 'shop-p3', name: 'Shree Ram Traders', owner: 'Ramawatar Sharma', mobile: '9425033333', address: 'Ganj Mandi Road, Pachore', marketId: 'mkt-pachore', routeId: 'route-pachore', connectedMarketId: 'cm-pachore-01', status: 'Customer', outstanding: 0, lastOrderKg: 25, lastOrderDate: '11-08-2026', highReturnWarning: false, lat: 23.7018, lng: 76.7150 },
  { id: 'shop-p4', name: 'Patel Kirana & Spices', owner: 'Dinesh Patel', mobile: '9425044444', address: 'Station Road, Pachore', marketId: 'mkt-pachore', routeId: 'route-pachore', connectedMarketId: 'cm-pachore-01', status: 'Customer', outstanding: 3400, lastOrderKg: 15, lastOrderDate: '11-08-2026', highReturnWarning: false, lat: 23.7042, lng: 76.7108 },
  { id: 'shop-p5', name: 'Maheshwari Super Market', owner: 'Gopal Maheshwari', mobile: '9425055555', address: 'Near Hospital Square, Pachore', marketId: 'mkt-pachore', routeId: 'route-pachore', connectedMarketId: 'cm-pachore-01', status: 'Customer', outstanding: 8900, lastOrderKg: 30, lastOrderDate: '11-08-2026', highReturnWarning: false, lat: 23.7050, lng: 76.7130 },
  { id: 'shop-p6', name: 'Balaji Traders', owner: 'Mukesh Choudhary', mobile: '9425066666', address: 'Subhash Marg, Pachore', marketId: 'mkt-pachore', routeId: 'route-pachore', connectedMarketId: 'cm-pachore-01', status: 'Customer', outstanding: 2100, lastOrderKg: 12, lastOrderDate: '11-08-2026', highReturnWarning: false, lat: 23.7012, lng: 76.7095 },
  { id: 'shop-p7', name: 'Royal General Store', owner: 'Aslam Khan', mobile: '9425077777', address: 'Old Bank Street, Pachore', marketId: 'mkt-pachore', routeId: 'route-pachore', connectedMarketId: 'cm-pachore-01', status: 'Customer', outstanding: 6700, lastOrderKg: 22, lastOrderDate: '11-08-2026', highReturnWarning: false, lat: 23.7029, lng: 76.7142 },
  { id: 'shop-p8', name: 'Shivam Masala Center', owner: 'Shivam Soni', mobile: '9425088888', address: 'Cloth Market, Pachore', marketId: 'mkt-pachore', routeId: 'route-pachore', connectedMarketId: 'cm-pachore-01', status: 'Customer', outstanding: 1400, lastOrderKg: 10, lastOrderDate: '11-08-2026', highReturnWarning: false, lat: 23.7038, lng: 76.7161 },
  { id: 'shop-p9', name: 'Om Wholesale Bhandar', owner: 'Prakash Saxena', mobile: '9425099999', address: 'Grain Market Gate, Pachore', marketId: 'mkt-pachore', routeId: 'route-pachore', connectedMarketId: 'cm-pachore-01', status: 'Customer', outstanding: 18500, lastOrderKg: 45, lastOrderDate: '11-08-2026', highReturnWarning: true, lat: 23.7061, lng: 76.7170 },
  { id: 'shop-p10', name: 'Vikas Provision Store', owner: 'Vikas Kushwaha', mobile: '9425000000', address: 'Nehru Colony, Pachore', marketId: 'mkt-pachore', routeId: 'route-pachore', connectedMarketId: 'cm-pachore-01', status: 'Lead', outstanding: 0, lastOrderKg: 0, lastOrderDate: null, highReturnWarning: false, lat: 23.7005, lng: 76.7182 },

  // Ashta Shops
  { id: 'shop-a1', name: 'Shree Krishna Traders', owner: 'Kamlesh Yadav', mobile: '9827011111', address: 'Kannod Road, Ashta', marketId: 'mkt-ashta', routeId: 'route-ashta', connectedMarketId: 'cm-ashta-01', status: 'Customer', outstanding: 4500, lastOrderKg: 20, lastOrderDate: '12-08-2026', highReturnWarning: false, lat: 23.0210, lng: 76.7215 },
  { id: 'shop-a2', name: 'National Provision', owner: 'Salim Sheikh', mobile: '9827022222', address: 'Main Market, Ashta', marketId: 'mkt-ashta', routeId: 'route-ashta', connectedMarketId: 'cm-ashta-01', status: 'Customer', outstanding: 9800, lastOrderKg: 28, lastOrderDate: '12-08-2026', highReturnWarning: false, lat: 23.0225, lng: 76.7230 },

  // Kalapipal Shops
  { id: 'shop-k1', name: 'Mahavir Kirana', owner: 'Kishore Jain', mobile: '9926011111', address: 'Station Road, Kalapipal', marketId: 'mkt-kalapipal', marketName: 'Kalapipal', routeId: 'route-kalapipal', connectedMarketId: 'cm-kalapipal-01', status: 'Customer', outstanding: 3200, openingOutstanding: 3200, lastOrderKg: 16, lastOrderDate: '13-08-2026', highReturnWarning: false, lat: 23.3312, lng: 76.8410 },

  // Shujalpur Shops
  { id: 'shop-s1', name: 'Mohit Kirana Store', owner: 'Mohit Sharma', mobile: '9926033333', address: 'Main Mandi, Shujalpur', marketId: 'mkt-shujalpur', marketName: 'Shujalpur', routeId: 'route-shujalpur', connectedMarketId: 'cm-shujalpur-01', status: 'Customer', outstanding: 4200, openingOutstanding: 4200, lastOrderKg: 24, lastOrderDate: '14-08-2026', highReturnWarning: false, lat: 23.4010, lng: 76.7020 },

  // Akodia Shops (Example from specifications)
  { id: 'shop-ak-1', name: 'Balaji Kirana Akodia', owner: 'Balaji Soni', mobile: '9826388415', address: 'Station Road, Akodia', marketId: 'mkt-akodia', marketName: 'Akodia', connectedMarketName: 'Akodia', status: 'Customer', outstanding: 4312, openingOutstanding: 4312, lastOrderKg: 18, lastOrderDate: '10-08-2026', highReturnWarning: false, lat: 23.3789, lng: 76.6012 },
  { id: 'shop-ak-2', name: 'Chowdhury Mart Akodia', owner: 'Ghanshyam Chowdhury', mobile: '9826388416', address: 'Bus Stand Square, Akodia', marketId: 'mkt-akodia', marketName: 'Akodia', connectedMarketName: 'Akodia', status: 'Customer', outstanding: 4367, openingOutstanding: 4367, lastOrderKg: 22, lastOrderDate: '12-08-2026', highReturnWarning: false, lat: 23.3795, lng: 76.6025 },
  { id: 'shop-ak-3', name: 'Dulichand, Sejalmal Traders Akodia', owner: 'Dulichand Jain', mobile: '9826388417', address: 'Grain Mandi, Akodia', marketId: 'mkt-akodia', marketName: 'Akodia', connectedMarketName: 'Akodia', status: 'Customer', outstanding: 2348, openingOutstanding: 2348, lastOrderKg: 14, lastOrderDate: '15-08-2026', highReturnWarning: false, lat: 23.3782, lng: 76.6038 },
  { id: 'shop-ak-4', name: 'Patidar Kirana Store Akodiya', owner: 'Suresh Patidar', mobile: '9826388418', address: 'Main Market, Akodiya', marketId: 'mkt-akodia', marketName: 'Akodia', connectedMarketName: 'Akodia', status: 'Customer', outstanding: 8569, openingOutstanding: 8569, lastOrderKg: 35, lastOrderDate: '16-08-2026', highReturnWarning: false, lat: 23.3790, lng: 76.6045 },
  { id: 'shop-ak-5', name: 'Ravi Kirana Akodia', owner: 'Ravi Verma', mobile: '9826388419', address: 'Chirai Square, Akodia', marketId: 'mkt-akodia', marketName: 'Akodia', connectedMarketName: 'Akodia', status: 'Customer', outstanding: 819, openingOutstanding: 819, lastOrderKg: 8, lastOrderDate: '18-08-2026', highReturnWarning: false, lat: 23.3801, lng: 76.6018 },
  { id: 'shop-ak-6', name: 'Vinayak Kirana Akodia', owner: 'Vinayak Sharma', mobile: '9826388420', address: 'Temple Road, Akodia', marketId: 'mkt-akodia', marketName: 'Akodia', connectedMarketName: 'Akodia', status: 'Customer', outstanding: 13381, openingOutstanding: 13381, lastOrderKg: 40, lastOrderDate: '19-08-2026', highReturnWarning: true, lat: 23.3810, lng: 76.6030 },
  { id: 'shop-ak-7', name: 'Abdul Aziz Kirana Akodiya', owner: 'Abdul Aziz', mobile: '9826388421', address: 'Old Post Office Road, Akodiya', marketId: 'mkt-akodia', marketName: 'Akodia', connectedMarketName: 'Akodia', status: 'Customer', outstanding: 0, openingOutstanding: 0, lastOrderKg: 12, lastOrderDate: '05-08-2026', highReturnWarning: false, lat: 23.3780, lng: 76.6010 },

  // Chakrod Shops
  { id: 'shop-ck-1', name: 'Chakrod Kirana Store', owner: 'Mohanlal Patidar', mobile: '9826388422', address: 'Main Road, Chakrod', marketId: 'mkt-chakrod', marketName: 'Chakrod', connectedMarketName: 'Chakrod', status: 'Customer', outstanding: 12450, openingOutstanding: 12450, lastOrderKg: 28, lastOrderDate: '12-08-2026', highReturnWarning: false, lat: 23.4120, lng: 76.6530 },
  { id: 'shop-ck-2', name: 'Mahakal Provision Chakrod', owner: 'Devendra Rathore', mobile: '9826388423', address: 'Panchayat Square, Chakrod', marketId: 'mkt-chakrod', marketName: 'Chakrod', connectedMarketName: 'Chakrod', status: 'Customer', outstanding: 18340, openingOutstanding: 18340, lastOrderKg: 36, lastOrderDate: '14-08-2026', highReturnWarning: false, lat: 23.4135, lng: 76.6542 },
  { id: 'shop-ck-3', name: 'Ganesh Traders Chakrod', owner: 'Ganesh Gupta', mobile: '9826388424', address: 'Bus Stop, Chakrod', marketId: 'mkt-chakrod', marketName: 'Chakrod', connectedMarketName: 'Chakrod', status: 'Customer', outstanding: 26095, openingOutstanding: 26095, lastOrderKg: 45, lastOrderDate: '16-08-2026', highReturnWarning: true, lat: 23.4110, lng: 76.6520 },
  { id: 'shop-ck-4', name: 'Shiv Kirana Chakrod', owner: 'Shivram Meena', mobile: '9826388425', address: 'Near School, Chakrod', marketId: 'mkt-chakrod', marketName: 'Chakrod', connectedMarketName: 'Chakrod', status: 'Customer', outstanding: 0, openingOutstanding: 0, lastOrderKg: 0, lastOrderDate: null, highReturnWarning: false, lat: 23.4105, lng: 76.6515 },

  // Jamner Shops
  { id: 'shop-jm-1', name: 'Jamner Spices & Kirana', owner: 'Kailash Meena', mobile: '9826388426', address: 'Market Road, Jamner', marketId: 'mkt-jamner', marketName: 'Jamner', connectedMarketName: 'Jamner', status: 'Customer', outstanding: 15400, openingOutstanding: 15400, lastOrderKg: 30, lastOrderDate: '10-08-2026', highReturnWarning: false, lat: 23.4510, lng: 76.7510 },
  { id: 'shop-jm-2', name: 'Krishna Kirana Jamner', owner: 'Krishna Murari', mobile: '9826388427', address: 'Old Bus Stand, Jamner', marketId: 'mkt-jamner', marketName: 'Jamner', connectedMarketName: 'Jamner', status: 'Customer', outstanding: 8900, openingOutstanding: 8900, lastOrderKg: 20, lastOrderDate: '12-08-2026', highReturnWarning: false, lat: 23.4525, lng: 76.7525 },

  // Gulana Shops
  { id: 'shop-gl-1', name: 'Gulana Super Mart', owner: 'Sanjay Patidar', mobile: '9826388428', address: 'Mandi Road, Gulana', marketId: 'mkt-gulana', marketName: 'Gulana', connectedMarketName: 'Gulana', status: 'Customer', outstanding: 9200, openingOutstanding: 9200, lastOrderKg: 25, lastOrderDate: '11-08-2026', highReturnWarning: false, lat: 23.3200, lng: 76.5500 },
  { id: 'shop-gl-2', name: 'Bajrang Kirana Gulana', owner: 'Bajrang Lal', mobile: '9826388429', address: 'Fort Gate, Gulana', marketId: 'mkt-gulana', marketName: 'Gulana', connectedMarketName: 'Gulana', status: 'Customer', outstanding: 4100, openingOutstanding: 4100, lastOrderKg: 15, lastOrderDate: '14-08-2026', highReturnWarning: false, lat: 23.3215, lng: 76.5515 },

  // Mohammad Kheda Shops
  { id: 'shop-mk-1', name: 'Mohammad Kheda Kirana', owner: 'Rafiq Mansuri', mobile: '9826388430', address: 'Main Bazar, Mohammad Kheda', marketId: 'mkt-mohammad-kheda', marketName: 'Mohammad Kheda', connectedMarketName: 'Mohammad Kheda', status: 'Customer', outstanding: 6300, openingOutstanding: 6300, lastOrderKg: 18, lastOrderDate: '13-08-2026', highReturnWarning: false, lat: 23.2800, lng: 76.6200 },

  // Bolai Shops
  { id: 'shop-bl-1', name: 'Bolai Provision Store', owner: 'Mahesh Sharma', mobile: '9826388431', address: 'Railway Gate, Bolai', marketId: 'mkt-bolai', marketName: 'Bolai', connectedMarketName: 'Bolai', status: 'Customer', outstanding: 5500, openingOutstanding: 5500, lastOrderKg: 16, lastOrderDate: '12-08-2026', highReturnWarning: false, lat: 23.3500, lng: 76.5800 },
  { id: 'shop-bl-2', name: 'Gupta Traders Bolai', owner: 'Ram Gupta', mobile: '9826388432', address: 'Station Road, Bolai', marketId: 'mkt-bolai', marketName: 'Bolai', connectedMarketName: 'Bolai', status: 'Customer', outstanding: 0, openingOutstanding: 0, lastOrderKg: 0, lastOrderDate: null, highReturnWarning: false, lat: 23.3510, lng: 76.5810 },
];

// Upgraded targets: now date-range based with unique IDs
export const INITIAL_TARGETS = [
  {
    id: 'tgt-1',
    marketerId: 'marketer-1',
    marketerName: 'Deepak Prajapati',
    targetType: 'Daily',
    startDate: '01-08-2026',
    endDate: '31-08-2026',
    dailyKg: 130,
    dailyCollection: 25000,
    dailyVisits: 30,
    dailyNewCustomers: 3,
    weeklyKg: 650,
    weeklyCollection: 125000,
    weeklyVisits: 150,
    weeklyNewCustomers: 15,
    monthlyKg: 2800,
    monthlyCollection: 540000,
    monthlyVisits: 650,
    monthlyNewCustomers: 60,
    active: true,
    createdDate: '01-08-2026',
  },
  {
    id: 'tgt-2',
    marketerId: 'marketer-2',
    marketerName: 'Vijay Verma',
    targetType: 'Daily',
    startDate: '01-08-2026',
    endDate: '31-08-2026',
    dailyKg: 120,
    dailyCollection: 22000,
    dailyVisits: 28,
    dailyNewCustomers: 2,
    weeklyKg: 600,
    weeklyCollection: 110000,
    weeklyVisits: 140,
    weeklyNewCustomers: 10,
    monthlyKg: 2600,
    monthlyCollection: 480000,
    monthlyVisits: 600,
    monthlyNewCustomers: 50,
    active: true,
    createdDate: '01-08-2026',
  },
  {
    id: 'tgt-3',
    marketerId: 'marketer-3',
    marketerName: 'Atul Meena',
    targetType: 'Daily',
    startDate: '01-08-2026',
    endDate: '31-08-2026',
    dailyKg: 110,
    dailyCollection: 20000,
    dailyVisits: 25,
    dailyNewCustomers: 2,
    weeklyKg: 550,
    weeklyCollection: 100000,
    weeklyVisits: 125,
    weeklyNewCustomers: 10,
    monthlyKg: 2400,
    monthlyCollection: 440000,
    monthlyVisits: 550,
    monthlyNewCustomers: 45,
    active: true,
    createdDate: '01-08-2026',
  },
  {
    id: 'tgt-4',
    marketerId: 'marketer-4',
    marketerName: 'Pankaj Malviya',
    targetType: 'Daily',
    startDate: '01-08-2026',
    endDate: '31-08-2026',
    dailyKg: 125,
    dailyCollection: 24000,
    dailyVisits: 30,
    dailyNewCustomers: 3,
    weeklyKg: 625,
    weeklyCollection: 120000,
    weeklyVisits: 150,
    weeklyNewCustomers: 15,
    monthlyKg: 2700,
    monthlyCollection: 520000,
    monthlyVisits: 620,
    monthlyNewCustomers: 55,
    active: true,
    createdDate: '01-08-2026',
  },
  {
    id: 'tgt-5',
    marketerId: 'marketer-5',
    marketerName: 'Vikash Meena',
    targetType: 'Daily',
    startDate: '01-08-2026',
    endDate: '31-08-2026',
    dailyKg: 115,
    dailyCollection: 21000,
    dailyVisits: 26,
    dailyNewCustomers: 2,
    weeklyKg: 575,
    weeklyCollection: 105000,
    weeklyVisits: 130,
    weeklyNewCustomers: 10,
    monthlyKg: 2500,
    monthlyCollection: 460000,
    monthlyVisits: 560,
    monthlyNewCustomers: 48,
    active: true,
    createdDate: '01-08-2026',
  },
];

export const INITIAL_HISTORICAL_DAILY_REPORTS = [
  {
    date: '11-08-2026',
    week: 'Week 2 Aug',
    month: 'August 2026',
    marketerId: 'marketer-1',
    marketerName: 'Deepak Sharma',
    marketId: 'mkt-pachore',
    marketName: 'Pachore',
    routeId: 'route-pachore',
    connectedMarketId: 'cm-pachore-01',
    connectedMarketName: 'Pachore',
    shopsPlanned: 30,
    shopsVisited: 28,
    customerConnected: 28,
    ordersCount: 20,
    salesKg: 210,
    salesValue: 48500,
    collectionValue: 32000,
    returnsKg: 12,
    returnsValue: 2800,
    newCustomersCount: 2,
    newLeadsCount: 3,
    fuelExpense: 160,
  },
  {
    date: '04-08-2026',
    week: 'Week 1 Aug',
    month: 'August 2026',
    marketerId: 'marketer-1',
    marketerName: 'Deepak Sharma',
    marketId: 'mkt-pachore',
    marketName: 'Pachore',
    routeId: 'route-pachore',
    connectedMarketId: 'cm-pachore-01',
    connectedMarketName: 'Pachore',
    shopsPlanned: 30,
    shopsVisited: 26,
    customerConnected: 26,
    ordersCount: 17,
    salesKg: 185,
    salesValue: 42000,
    collectionValue: 28500,
    returnsKg: 15,
    returnsValue: 3400,
    newCustomersCount: 1,
    newLeadsCount: 2,
    fuelExpense: 160,
  },
];
